@startuml test

class Sequencer <Sequencer> {
}

class OscA <Oscillator> {
	- shape: saw
}

class OscB <Oscillator> {
	- shape: square
}

class EnvA <ADSREnvelope> {
	- attack: .1
	- decay: .1
	- sustain: .5
	- release: .1
}

class EnvB <ADSREnvelope> {
	- attack: .5
	- decay: .3
	- sustain: .4
	- release: .2
}

class Mix <Mixer> {
	- cv: .5
}

class Output <Output> {
}

class Lfo1 <Oscillator> {
	- shape: triangle
	- frequency: 12.
}

class Filter <Filter> {
	- type: lowpass
	- resonance: .5
}

class LfoFilterTransform <Math> {
	- formula: output = .5+.1*input
}

Sequencer "NoteOnOff1" *-- "onOff" EnvA
Sequencer "NoteOnOff2" *-- "onOff" EnvB
Sequencer "NoteFrequency1" *-- "frequency" OscA
Sequencer "NoteFrequency2" *-- "frequency" OscB

OscA "output" *-- "input1" EnvA
OscB "output" *-- "input1" EnvB
EnvA "output" *-- "input1" Mix
EnvB "output" *-- "input2" Mix
Mix "output" *-- "input" Filter

Lfo1 "output" *-- "input" LfoFilterTransform
LfoFilterTransform "output" *-- "cutoff" Filter
Filter "output" *-- "input" Output

@enduml
